name: intelliplan_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.12

  intelliplan_api:
    path: ../intelliplan_api

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  openapi_repository_annotations: ^1.1.0
  built_value: ^8.4.4
  flutter_bloc: ^8.1.2
  list_bloc: ^3.1.0
  flutter_list_bloc: ^4.1.0
  built_collection: ^5.1.1
  freezed: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  openapi_repository: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  built_value_generator: ^8.4.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
